### ISSUE TITLE
Run in the background when the Pomodoro is actived 

### ISSUE THREAD

**Issue by alainm23** [naaando/rush#10]
Congratulations for your application, it is very useful, please add this feature.

**Comment by naaando** [comment]
I think elementary don't handle this so well, what if the user wants to end interaction with the app and it is still running after closing, I can't rely on a system tray. If you need this feature specifically I can implement with a command line parameter or a setting but I don't think I'll set this as default behavior.

**Comment by alainm23** [comment]
I'm sorry, I was not very clear. 
my idea is while the Pomodoro is active, if the user closes the application, make the application run in the background, if the user for the Pomodoro, that the application is completely closed.

**Comment by naaando** [comment]
Yes, I understood but still don't think it is a good fit, the only native application for eOS that has this behavior is Noise(Music) and I still find it annoying that I have to pause to close it. As this feature isn't that hard to implement I can release it under a disabled by default setting for now.
