### ISSUE TITLE
Add translation capability

### ISSUE THREAD

**Issue by NathanBnm** [naaando/rush#11]

**Comment by naaando** [comment]
Translatable it is @NathanBnm , I _rushed_ 😂️ to publish it on AppCenter and missed important things like this, once again I appreciate your effort in keeping apps accessible for people that don't domain english.

**Comment by NathanBnm** [comment]
Thank you :smile: I understand, it's good too to make a release as soon as possible, because you want your app to be published ^^. The most important thing is that you do the updates afterwards.
