### ISSUE TITLE
Change the beeping sound to a more friendly sound

### ISSUE THREAD

**Issue by ghost** [naaando/rush#18]
Hello Fernando, I enjoy your app.

What I do not enjoy is that 1980s G-Shock beeping sound. Now, this is something very nitpicked but it's something I still wanted to suggest.

iOS has some nice sounds for alarms and stuff, maybe you can be inspired by them

Cheers, and keep developing good apps.

**Comment by naaando** [comment]
Hi Adrian, my app uses default system sound for the beep, which at least on elementary OS is shipped by freedesktop, you can override it with something you like moving to(if you're using elementary) /usr/share/sounds/elementary with the format wav, oga, ogg or requesting for your operational system developers to ship a better...
